### ISSUE TITLE
Review: User Authentication

### ISSUE THREAD

**Issue by SkyisAakash** [SkyisAakash/MeetUs#3]

**Comment by s-pangburn** [comment]
Great job Aakash! This looks really good! 

- [x] In your nav, "Login" and "Signup" should be aligned with "Start a new group". Right now, they're a little higher up.
- [x] Login and Signup both need just a little more padding on the left (but the right is fine)
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
- [x] I know you're just cloning Meetup, but honestly you should just get rid of that lock image on the auth form, it just looks ugly 😅 
- [x] More padding on the top and bottom of your login/signup form, too!
- [x] Also I did say to make the buttons take up 100% of the width, but I actually meant to make them have just a little padding on each side, like the inputs for username and password. Ideally, they'd all be exactly like the inputs in width.
- [x] If "Keep me signed in" doesn't do anything, you should remove it.
- [x] Your **Login** title is aligned-left while your **Sign up** is centered. Either both should be aligned-left or both should be centered (again, I know Meetup does it the way you did it, but it's ugly, so please don't do it that way, haha)
- [x] Your "Already a member?" and "Not registered with us yet?" are in completely different places. They should both be in the same place on both forms (with identical styling)
- [x] After logging in, your user icon should be at least twice as large. It should also be aligned with "Start a new group"
- [x] You don't have a uniqueness validation for email
- [x] Pressing Enter on your login form doesn't log you in.
- [x] If the dropdown was open when I logged out, it's still open when I log back in, even if I didn't click anything (Hint: use componentWillUnmount)

**Comment by s-pangburn** [comment]
Hi Aakash! In the future, you should wait for me to close the issue when it comes to PA Reviews specifically. That being said, I actually have a few more points I'd like you to address 🙂 

- [x] Your avatar in the nav for the dropdown should set the `cursor: pointer` CSS property on `::hover`. This changes your cursor into the pointer hand, which tells the user that the avatar is clickable.
- [x] The avatar should have just a little more padding on the right side. It's too close to the edge.
- [x] "Log in" and "Sign up" in the nav still do not align with "Start a new group" properly.
- [x] Your demo login button text should be a little bigger so that people with poor eyesight can read. Maybe as big as the Login/Signup button or a little smaller.

**Comment by s-pangburn** [comment]
Looks good Aakash! Awesome job 🙂
